shortener/shortener_project/shortener/urls.py
from django.urls import path
from . import views

app_name = 'shortener'
urlpatterns = [
    path('', views.InputsView.as_view(), name="inputs"),
    path('post/', views.post, name="post"),
    path('<str:short_code>/', views.redirect, name="redirect"),
    path('<str:short_code>/details', views.details, name="details")   
]

shortener/shortener_project/shortener_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shortener/', include("shortener.urls")),
]

shortener/shortener_project/shortener/models.py
from django.db import models
from django.core.validators import MinLengthValidator


# Create your models here.
class Url(models.Model):
    long_url = models.CharField(max_length=2000)
    short_code = models.CharField(max_length=5, validators=[MinLengthValidator(5)], )
    
    def __str__(self):
        return self.long_url

    

shortener/shortener_project/shortener/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils.crypto import get_random_string


from .models import Url


def inputs(request):
    return render(request, 'shortener/inputs.html')

class InputsView(generic.TemplateView):
    template_name = 'shortener/inputs.html'


def details(request, short_code):
    url = get_object_or_404(Url, short_code=short_code)
    return render(request, 'shortener/details.html', {'url':url })



def post(request):
    try:
        url = Url.objects.get(long_url=request.POST['long_url'])
    except Url.DoesNotExist:
        url = Url()
        url.long_url = request.POST['long_url'] 
        url.short_code = request.POST['short_code']
        url.save()
        return HttpResponseRedirect(reverse('shortener:details', args=(url.short_code, )))


def redirect(request, short_code):
    url = get_object_or_404(Url, short_code=short_code)
    return HttpResponseRedirect(url.long_url)

shortener/shortener_project/shortener/templates/shortener/details.html
<h1>URL SHORTENER</h1>

<div style="display: flex;">
    <p style="margin-right: 20px"><strong>Original url:</strong></p>
    <p>{{url.long_url}}</p>
</div>

<div style="display: flex;">
    <p style="margin-right: 40px"><strong>Short url:</strong></p>
    <p><a href="{% url 'shortener:redirect' url.short_code %}">http://127.0.0.1:8000/shortener/{{url.short_code}}</a></p>
</div>

shortener/shortener_project/shortener/templates/shortener/inputs.html
<h1>Shorten your url</h1>
{% if messages %}
{% for message in messages %}
<p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
{% endif %}
{{text}}
<form action="{% url 'shortener:post' %}" method="post">
    {% csrf_token %}
    <input type="url" name="long_url" id="long_url" placeholder="Your url">
    <input type="submit" name="shortener_submit" id="shortener_submit" value="Shorten">
</form>